version: "3.8"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: forgebot
    volumes:
      - db_data:/var/lib/postgresql/data
  bot:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db_data:
